baseurl                 = "https://rancherjp.github.io/site/"
languageCode            = "ja-jp"
title                   = "Rancher JP"
hasCJKLanguage          = true
copyright               = "© 2016 Rancher JP"
pygmentscodefences      = true
pygmentsstyle           = "borland"

[permalinks]
    blog                = "/blog/:year/:month/:day/:slug/"
    docs                = "/docs/:slug/"
    post                = "/content/:year/:month/:day/:slug/"
    releasenote         = "/releasenote/:slug/"
    page                = "/:slug/"

[taxonomies]
    tag                 = "tags"
    category            = "categories"
    archive             = "archives"


# The header menu will appear as an inline-list at the top right of the page
[[menu.header]]
    name                = "Home"
    weight              = 1
    url                 = "/"
[[menu.header]]
    name                = "Docs"
    weight              = 2
    url                 = "/docs"
[[menu.header]]
    name                = "Blog"
    weight              = 3
    url                 = "/blog"
[[menu.header]]
    name                = "Q&A"
    weight              = 4
    url                 = "/qa"
[[menu.header]]
    name                = "Release Note"
    weight              = 5
    url                 = "/releasenote"
[[menu.header]]
    name                = "Archives"
    weight              = 6
    url                 = "/archives"
[[menu.header]]
    name                = "About"
    weight              = 8
    url                 = "/about"

[params]
    author              = "Rancher JP"
    keywords            = ["Rancher", "RancherJP"]
    description         = "Rancher Japan Community page"
    noindex             = "noindex"



# Social media icons and links that appear in the footer
[social]
    twitter             = "https://twitter.com/rancherjp"
    facebook            = "https://www.facebook.com/rancherjp"
    slack               = "https://rancherjp.herokuapp.com"
