baseurl                 = "http://www.rancher.jp/site/"
languageCode            = "ja-jp"
title                   = "Rancher JP"
hasCJKLanguage          = true
copyright               = "© 2016 Rancher JP"
##pygmentscodefences      = true
pygmentsuseclasses      = true
pygmentsstyle           = "borland"
PygmentsOptions         = "linenos=table,nobackground=true"

[permalinks]
    blog                = "/blog/:year/:month/:day/:slug/"
    study               = "/study/:slug/"
    docs                = "/docs/:slug/"
    traslated           = "/traslated/:slug/"
    post                = "/content/:year/:month/:day/:slug/"
    releasenote         = "/releasenote/:slug/"
    page                = "/:slug/"

[taxonomies]
    tag                 = "tags"
    category            = "categories"
    archive             = "archives"


# The header menu will appear as an inline-list at the top right of the page
[[menu.header]]
    name                = "Home"
    weight              = 1
    url                 = "/"
[[menu.header]]
    name                = "Docs"
    weight              = 2
    url                 = "/docs"
[[menu.header]]
    name                = "Study"
    weight              = 3
    url                 = "/study"
[[menu.header]]
    name                = "Traslated"
    weight              = 4
    url                 = "/traslated"
[[menu.header]]
    name                = "Event"
    weight              = 5
    url                 = "/event"
[[menu.header]]
    name                = "Q&A"
    weight              = 6
    url                 = "/qa"
[[menu.header]]
    name                = "Release Note"
    weight              = 7
    url                 = "/releasenote"
[[menu.header]]
    name                = "Archives"
    weight              = 9
    url                 = "/archives"
[[menu.header]]
    name                = "About"
    weight              = 10
    url                 = "/about"

[params]
    author              = "Rancher JP"
    google_analytics    = "UA-90391346-1"
    keywords            = ["Rancher", "RancherJP"]
    description         = "Rancher Japan Community page"
    noindex             = "noindex"



# Social media icons and links that appear in the footer
[social]
    twitter             = "https://twitter.com/rancherjp"
    facebook            = "https://www.facebook.com/rancherjp"
    slack               = "https://rancherjp.herokuapp.com"
